apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  capacity:
    storage: 8Gi
#  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Delete
#  storageClassName: local-storage
  storageClassName: manual
  hostPath:
    path: "/pv001"
#  local:
#    path: /pv001
#  nodeAffinity:
#    required:
#      nodeSelectorTerms:
#        - matchExpressions:
#            - key: kubenetes.io/hostname
#              operator: In
#              values:
#                - bms23-k8n1
#                - bms24-k8n2
